INSERT INTO CURRENCY_EXCHANGE (ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT) VALUES (10001,'USD','INR',65,'');
INSERT INTO CURRENCY_EXCHANGE (ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT) VALUES (10002,'EUR','INR',90,'');
INSERT INTO CURRENCY_EXCHANGE (ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT) VALUES (10003,'GBP','INR',80,'');